/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}

export type UserRole = { __kind__: "admin" } | { __kind__: "user" } | { __kind__: "guest" };

export interface Article {
    id: bigint;
    title: string;
    content: string;
    category: string;
    imageUrl: string;
    author: string;
    excerpt: string;
    date: string;
    isBreaking: boolean;
    isSlider: boolean;
    isPublished: boolean;
}

export interface backendInterface {
    _initializeAccessControlWithSecret: (userSecret: string) => Promise<undefined>;
    addArticle: (title: string, content: string, category: string, imageUrl: string, author: string, excerpt: string, date: string, isBreaking: boolean, isSlider: boolean, isPublished: boolean) => Promise<bigint>;
    addCategory: (category: string) => Promise<undefined>;
    assignCallerUserRole: (user: Principal, role: UserRole) => Promise<undefined>;
    deleteArticle: (id: bigint) => Promise<boolean>;
    getAllArticles: () => Promise<Article[]>;
    getArticleById: (id: bigint) => Promise<Article | undefined>;
    getArticlesByCategory: (category: string) => Promise<Article[]>;
    getBreakingArticles: () => Promise<Article[]>;
    getBreakingNewsText: () => Promise<string>;
    getCallerUserRole: () => Promise<UserRole>;
    getCategories: () => Promise<string[]>;
    getPublishedArticles: () => Promise<Article[]>;
    getSliderArticles: () => Promise<Article[]>;
    isCallerAdmin: () => Promise<boolean>;
    removeCategory: (category: string) => Promise<undefined>;
    setBreakingNewsText: (text: string) => Promise<undefined>;
    updateArticle: (id: bigint, title: string, content: string, category: string, imageUrl: string, author: string, excerpt: string, date: string, isBreaking: boolean, isSlider: boolean, isPublished: boolean) => Promise<boolean>;
}

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}

    async _initializeAccessControlWithSecret(userSecret: string): Promise<undefined> {
        return await (this.actor as any)._initializeAccessControlWithSecret(userSecret);
    }
    async addArticle(title: string, content: string, category: string, imageUrl: string, author: string, excerpt: string, date: string, isBreaking: boolean, isSlider: boolean, isPublished: boolean): Promise<bigint> {
        return await (this.actor as any).addArticle(title, content, category, imageUrl, author, excerpt, date, isBreaking, isSlider, isPublished);
    }
    async addCategory(category: string): Promise<undefined> {
        return await (this.actor as any).addCategory(category);
    }
    async assignCallerUserRole(user: Principal, role: UserRole): Promise<undefined> {
        const candidRole = role.__kind__ === 'admin' ? { admin: null } : role.__kind__ === 'user' ? { user: null } : { guest: null };
        return await (this.actor as any).assignCallerUserRole(user, candidRole);
    }
    async deleteArticle(id: bigint): Promise<boolean> {
        return await (this.actor as any).deleteArticle(id);
    }
    async getAllArticles(): Promise<Article[]> {
        return await (this.actor as any).getAllArticles();
    }
    async getArticleById(id: bigint): Promise<Article | undefined> {
        const result = await (this.actor as any).getArticleById(id);
        return result.length > 0 ? result[0] : undefined;
    }
    async getArticlesByCategory(category: string): Promise<Article[]> {
        return await (this.actor as any).getArticlesByCategory(category);
    }
    async getBreakingArticles(): Promise<Article[]> {
        return await (this.actor as any).getBreakingArticles();
    }
    async getBreakingNewsText(): Promise<string> {
        return await (this.actor as any).getBreakingNewsText();
    }
    async getCallerUserRole(): Promise<UserRole> {
        const result = await (this.actor as any).getCallerUserRole();
        if ('admin' in result) return { __kind__: 'admin' };
        if ('user' in result) return { __kind__: 'user' };
        return { __kind__: 'guest' };
    }
    async getCategories(): Promise<string[]> {
        return await (this.actor as any).getCategories();
    }
    async getPublishedArticles(): Promise<Article[]> {
        return await (this.actor as any).getPublishedArticles();
    }
    async getSliderArticles(): Promise<Article[]> {
        return await (this.actor as any).getSliderArticles();
    }
    async isCallerAdmin(): Promise<boolean> {
        return await (this.actor as any).isCallerAdmin();
    }
    async removeCategory(category: string): Promise<undefined> {
        return await (this.actor as any).removeCategory(category);
    }
    async setBreakingNewsText(text: string): Promise<undefined> {
        return await (this.actor as any).setBreakingNewsText(text);
    }
    async updateArticle(id: bigint, title: string, content: string, category: string, imageUrl: string, author: string, excerpt: string, date: string, isBreaking: boolean, isSlider: boolean, isPublished: boolean): Promise<boolean> {
        return await (this.actor as any).updateArticle(id, title, content, category, imageUrl, author, excerpt, date, isBreaking, isSlider, isPublished);
    }
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
